name: Mike Plays with The Grid
favicon: null
layout_spectrum: 0.25773
typography_spectrum: 0.37732
title: Curated items from the world of Mike
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#99c9e9'
    - '#ff0045'
    - '#ffc400'
    - '#18232b'
    - '#ff78b2'
  brandStrength: 0.6211847998201847
  lightness: 0.3125
  saturation: 0.14160993765108287
  rhythmicContrast: 0.25
purpose: []
